name: "Checks PR body and payload"
on:
  pull_request:
    types: [opened, edited, ready_for_review, synchronize]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        with:
          github-token: ${{github.token}}
          bodyContains: "[x]"
          bodyDoesNotContain: "Delete this|your own"
          diffContains: ""
