name: "Check contributors file additions"
on:
  pull_request:
    types: [opened, edited]
    paths:
      - CONTRIBUTORS.md

jobs:
  check_pr:
    name: "Checks of dev version"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v10
        with:
          github-token: ${{github.token}}
          linesChanged: 2
          filesChanged: 1
