name: "Check PR for word - v2"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v3
        with:
          github-token: ${{github.token}}
          bodyContains: "[x]"
          bodyDoesNotContain: "Delete this"
          diffContains: ""
          filesChanged: 1
          linesChanged: 1
