name: "Master check PR data"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@master
        with:
          github-token: ${{github.token}}
          bodyContains: "[x]"
          bodyDoesNotContain: ["your", "own"]
          diffContains: ""
          linesChanged: 1
