name: "Check PR for word"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action
        with:
          github-token: ${{github.token}}
          bodyContains: "[x]"
          diffContains: ""
          linesChanged: 1
