name: "Master check PR data"
on:
  pull_request:
    types: [opened, edited, ready_for_review]
  push:

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@master
        with:
          github-token: ${{github.token}}
          bodyContains: "[x]"
          bodyDoesNotContain: "your|own"
          diffDoesNotContain: "TODO"
          linesChanged: 1
