name: "Workflow for testing"
on:
  pull_request:
  branches:
    - 'JJ-patch-*'

jobs:
  check_pr:
    name: "Checks dev version"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@master
        with:
          github-token: ${{github.token}}
          bodyContains: "[x]"
          bodyDoesNotContain: "your|own"
          diffDoesNotContain: "TODO"
          linesChanged: 1
