name: "Workflow for testing"
on:
  pull_request:
    types:
      [opened, edited, assigned, closed, review_requested, ready_for_review]
    branches:
      - JJ-patch-*

jobs:
  check_pr:
    name: "Checks dev version"
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@master
        with:
          github-token: ${{github.token}}
          bodyContains: "[x]"
          bodyDoesNotContain: "your|own"
          diffDoesNotContain: "TODO"
          linesChanged: 1
